replicaCount: 1

image:
  registry: ghcr.io
  repository: szdobnikova-code/kbot
  tag: v1.0.2-afa76f7
  os: linux
  arch: amd64
  pullPolicy: IfNotPresent

telegram:
  secretName: kbot-secret

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

resources: {}
