apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kbot.fullname" . }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kbot.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kbot.serviceAccountName" . }}
      containers:
        - name: "{{ .Release.Name }}"
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.image.os }}-{{ .Values.image.arch }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - "kbot"
          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}"
                  key: TELE_TOKEN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
