apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELE_TOKEN: {{ .Values.secret.TELE_TOKEN | quote }}
