apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.teleToken.secretName }}
  labels:
    {{- include "kbot.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.teleToken.token | b64enc | quote }}
